name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Instalar dependencias del sistema necesarias
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libssl-dev \
            pkg-config \
            libgtk-4-dev \
            libcairo2-dev \
            libglib2.0-dev \
            libpango1.0-dev \
            libgdk-pixbuf-2.0-dev

      # Toolchain estable y caché para acelerar builds
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      # Build solo CLI primero (más rápido y confiable)
      - name: Build CLI (debug)
        run: cargo build --verbose

      # Build con GUI si las dependencias están disponibles
      - name: Build GUI (debug)
        run: cargo build --features gui --verbose

      # Run tests (sin GUI features para evitar problemas de display)
      - name: Run tests
        run: cargo test --verbose

  binary:
    name: Build release binary
    runs-on: ubuntu-latest
    needs: check
    # Solo construir binario en push a main (no en PRs)
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      # Instalar dependencias del sistema para release
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libssl-dev \
            pkg-config \
            libgtk-4-dev \
            libcairo2-dev \
            libglib2.0-dev \
            libpango1.0-dev \
            libgdk-pixbuf-2.0-dev

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      # Build release CLI y GUI
      - name: Build CLI (release)
        run: cargo build --release --verbose

      - name: Build GUI (release)
        run: cargo build --release --features gui --verbose

      # Sube los binarios compilados como artifact del workflow
      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: ui-openvpn-linux-${{ runner.os }}-x86_64
          path: |
            target/release/*
          if-no-files-found: error

      # OPCIONAL: si prefieres usar rust-build.action para empaquetar/targets cruzados,
      # comenta el bloque de build+upload anterior y descomenta este:
      #
      # - name: Build with rust-build.action
      #   uses: rust-build/rust-build.action@v1.4.5
      #   with:
      #     # Target de salida (cambia si necesitas otro)
      #     RUSTTARGET: x86_64-unknown-linux-gnu
      #     TOOLCHAIN_VERSION: stable
      #     # Evita crear un GitHub Release en cada push
      #     UPLOAD_MODE: none
      #
      # - name: Upload packaged artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: ui-openvpn-linux-${{ runner.os }}-x86_64
      #     path: |
      #       dist/**
      #       *.zip
      #       *.tar.*